<a href="https://colab.research.google.com/github/pbansari25/ROMAN_TO_INTEGER/blob/main/Decision_Trees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('/content/vertebrate.csv',header='infer')

In [3]:
data

,Name,Warm-blooded,Gives Birth,Aquatic Creature,Aerial Creature,Has Legs,Hibernates,Class
0,human,1,1,0,0,1,0,mammals
1,python,0,0,0,0,0,1,reptiles
2,salmon,0,0,1,0,0,0,fishes
3,whale,1,1,1,0,0,0,mammals
4,frog,0,0,1,0,1,1,amphibians
5,komodo,0,0,0,0,1,0,reptiles
6,bat,1,1,0,1,1,1,mammals
7,pigeon,1,0,0,1,1,0,birds
8,cat,1,1,0,0,1,0,mammals
9,leopard shark,0,1,1,0,0,0,fishes
10,turtle,0,0,1,0,1,0,reptiles
11,penguin,1,0,1,0,1,0,birds
12,porcupine,1,1,0,0,1,1,mammals
13,eel,0,0,1,0,0,0,fishes
14,salamander,0,0,1,0,1,1,amphibians